//! VERZ Link V2 measurement-lab primitives.
//!
//! The original lab protocol carries generated bytes. The `tunnel` module
//! carries real IPv4 packets between operating-system network interfaces.

pub mod bond;
pub mod brain;
pub mod direct;
pub mod reorder;
mod tcp_metrics;
pub mod tunnel;

use std::{
    fs,
    net::{SocketAddr, UdpSocket as StdUdpSocket},
    path::Path,
    time::{Duration, Instant},
};

use anyhow::{Context, Result, bail};
use chacha20poly1305::{
    ChaCha20Poly1305, KeyInit, Nonce,
    aead::{Aead, Payload},
};
use hkdf::Hkdf;
use serde::Serialize;
use sha2::Sha256;
use tokio::net::UdpSocket;

pub const MAGIC: [u8; 4] = *b"VZL1";
pub const VERSION: u8 = 1;
pub const OUTER_LEN: usize = 32;
pub const INNER_LEN: usize = 20;
pub const TAG_LEN: usize = 16;
pub const MAX_DATAGRAM: usize = 1200;
pub const DEFAULT_PAYLOAD: usize = 900;
pub const DEFAULT_PORT: u16 = 39_000;
pub const REPLAY_WIDTH: u64 = 4_096;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum Kind {
    Data = 1,
    Ack = 2,
    Probe = 3,
    Pong = 4,
}

impl TryFrom<u8> for Kind {
    type Error = anyhow::Error;

    fn try_from(value: u8) -> Result<Self> {
        match value {
            1 => Ok(Self::Data),
            2 => Ok(Self::Ack),
            3 => Ok(Self::Probe),
            4 => Ok(Self::Pong),
            _ => bail!("unknown packet kind"),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum Role {
    Client = 0,
    Relay = 1,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct SessionId(pub [u8; 16]);

impl SessionId {
    pub fn random() -> Self {
        Self(rand::random())
    }
}

#[derive(Clone, Copy, Debug)]
pub struct Outer {
    pub kind: Kind,
    pub path: u8,
    pub session: SessionId,
    pub counter: u64,
}

impl Outer {
    pub fn parse(packet: &[u8]) -> Result<Self> {
        if !(OUTER_LEN + INNER_LEN + TAG_LEN..=MAX_DATAGRAM).contains(&packet.len()) {
            bail!("invalid datagram length");
        }
        if packet[..4] != MAGIC || packet[4] != VERSION || packet[7] != 0 {
            bail!("invalid protocol header");
        }
        let kind = Kind::try_from(packet[5])?;
        let path = packet[6];
        if path > 1 {
            bail!("invalid path identifier");
        }
        let mut session = [0_u8; 16];
        session.copy_from_slice(&packet[8..24]);
        let counter = u64::from_be_bytes(packet[24..32].try_into()?);
        Ok(Self {
            kind,
            path,
            session: SessionId(session),
            counter,
        })
    }

    fn encode(self) -> [u8; OUTER_LEN] {
        let mut output = [0_u8; OUTER_LEN];
        output[..4].copy_from_slice(&MAGIC);
        output[4] = VERSION;
        output[5] = self.kind as u8;
        output[6] = self.path;
        output[8..24].copy_from_slice(&self.session.0);
        output[24..32].copy_from_slice(&self.counter.to_be_bytes());
        output
    }
}

#[derive(Debug)]
pub struct Message {
    pub kind: Kind,
    pub flow: u8,
    pub sequence: u64,
    pub echo_micros: u64,
    pub payload: Vec<u8>,
}

#[derive(Debug)]
pub struct ReplayWindow {
    width: u64,
    high: Option<u64>,
    // Exact counter tags in a fixed ring avoid scanning the entire window for
    // each authenticated packet. Tags distinguish a reused slot from a replay.
    seen: Vec<Option<u64>>,
}

impl ReplayWindow {
    pub fn new(width: u64) -> Self {
        assert!(width > 0);
        Self {
            width,
            high: None,
            seen: vec![None; usize::try_from(width).expect("replay window fits memory")],
        }
    }

    pub fn contains(&self, counter: u64) -> bool {
        self.high
            .is_some_and(|high| counter <= high && high - counter >= self.width)
            || self.seen[(counter % self.width) as usize] == Some(counter)
    }

    pub fn mark(&mut self, counter: u64) -> bool {
        if self.contains(counter) {
            return false;
        }
        let high = self.high.map_or(counter, |value| value.max(counter));
        self.high = Some(high);
        self.seen[(counter % self.width) as usize] = Some(counter);
        true
    }
}

pub struct Channel {
    session: SessionId,
    path: u8,
    tx_counter: u64,
    tx: ChaCha20Poly1305,
    rx: ChaCha20Poly1305,
    replay: ReplayWindow,
}

impl Channel {
    pub fn new(secret: &[u8; 32], session: SessionId, path: u8, role: Role) -> Result<Self> {
        if path > 1 {
            bail!("path must be 0 or 1");
        }
        let derive = |direction: Role| -> Result<[u8; 32]> {
            let hkdf = Hkdf::<Sha256>::new(Some(&session.0), secret);
            let mut key = [0_u8; 32];
            let info = [b"verz-link-lab-v1/".as_slice(), &[direction as u8, path]].concat();
            hkdf.expand(&info, &mut key)
                .map_err(|_| anyhow::anyhow!("key derivation failed"))?;
            Ok(key)
        };
        let tx = ChaCha20Poly1305::new((&derive(role)?).into());
        let peer = if role == Role::Client {
            Role::Relay
        } else {
            Role::Client
        };
        let rx = ChaCha20Poly1305::new((&derive(peer)?).into());
        Ok(Self {
            session,
            path,
            tx_counter: 0,
            tx,
            rx,
            replay: ReplayWindow::new(REPLAY_WIDTH),
        })
    }

    pub fn seal(
        &mut self,
        kind: Kind,
        flow: u8,
        sequence: u64,
        echo_micros: u64,
        payload: &[u8],
    ) -> Result<Vec<u8>> {
        if flow > 1 || (kind == Kind::Data) != !payload.is_empty() {
            bail!("invalid message body");
        }
        if OUTER_LEN + INNER_LEN + payload.len() + TAG_LEN > MAX_DATAGRAM {
            bail!("payload exceeds lab MTU");
        }
        let counter = self.tx_counter;
        self.tx_counter = self
            .tx_counter
            .checked_add(1)
            .context("channel nonce exhausted")?;
        let outer = Outer {
            kind,
            path: self.path,
            session: self.session,
            counter,
        };
        let header = outer.encode();
        let mut body = Vec::with_capacity(INNER_LEN + payload.len());
        body.push(flow);
        body.extend_from_slice(&[0_u8; 3]);
        body.extend_from_slice(&sequence.to_be_bytes());
        body.extend_from_slice(&echo_micros.to_be_bytes());
        body.extend_from_slice(payload);
        let nonce_bytes = nonce(counter);
        let encrypted = self
            .tx
            .encrypt(
                Nonce::from_slice(&nonce_bytes),
                Payload {
                    msg: &body,
                    aad: &header,
                },
            )
            .map_err(|_| anyhow::anyhow!("encryption failed"))?;
        Ok([header.as_slice(), encrypted.as_slice()].concat())
    }

    pub fn open(&mut self, packet: &[u8]) -> Result<Message> {
        let outer = Outer::parse(packet)?;
        if outer.session != self.session
            || outer.path != self.path
            || self.replay.contains(outer.counter)
        {
            bail!("wrong session, path, or replayed counter");
        }
        let nonce_bytes = nonce(outer.counter);
        let plaintext = self
            .rx
            .decrypt(
                Nonce::from_slice(&nonce_bytes),
                Payload {
                    msg: &packet[OUTER_LEN..],
                    aad: &packet[..OUTER_LEN],
                },
            )
            .map_err(|_| anyhow::anyhow!("packet authentication failed"))?;
        if plaintext.len() < INNER_LEN || plaintext[1..4] != [0_u8; 3] {
            bail!("invalid encrypted body");
        }
        let flow = plaintext[0];
        if flow > 1 {
            bail!("invalid flow identifier");
        }
        let sequence = u64::from_be_bytes(plaintext[4..12].try_into()?);
        let echo_micros = u64::from_be_bytes(plaintext[12..20].try_into()?);
        let payload = plaintext[INNER_LEN..].to_vec();
        if (outer.kind == Kind::Data) != !payload.is_empty() {
            bail!("invalid payload for message kind");
        }
        if !self.replay.mark(outer.counter) {
            bail!("replayed packet");
        }
        Ok(Message {
            kind: outer.kind,
            flow,
            sequence,
            echo_micros,
            payload,
        })
    }
}

fn nonce(counter: u64) -> [u8; 12] {
    let mut output = [0_u8; 12];
    output[4..].copy_from_slice(&counter.to_be_bytes());
    output
}

pub fn synthetic_payload(sequence: u64, size: usize) -> Vec<u8> {
    let seed = sequence.to_be_bytes();
    (0..size)
        .map(|index| seed[index % seed.len()] ^ (index as u8).wrapping_mul(31))
        .collect()
}

pub fn load_secret(path: &Path) -> Result<[u8; 32]> {
    let value =
        fs::read_to_string(path).with_context(|| format!("read secret {}", path.display()))?;
    let bytes = hex::decode(value.trim()).context("secret must be hexadecimal")?;
    bytes
        .try_into()
        .map_err(|_| anyhow::anyhow!("secret must contain exactly 32 bytes"))
}

pub fn monotonic_micros(start: Instant) -> u64 {
    start.elapsed().as_micros().min(u64::MAX as u128) as u64
}

#[derive(Clone, Debug, Serialize)]
pub struct PathState {
    pub path: u8,
    pub interface: String,
    pub source: SocketAddr,
    pub samples: u64,
    pub srtt_ms: Option<f64>,
    pub rtt_variation_ms: f64,
    pub minimum_rtt_ms: Option<f64>,
    #[serde(skip)]
    pub last_response: Option<Instant>,
}

impl PathState {
    pub fn new(path: u8, interface: String, source: SocketAddr) -> Self {
        Self {
            path,
            interface,
            source,
            samples: 0,
            srtt_ms: None,
            rtt_variation_ms: 0.0,
            minimum_rtt_ms: None,
            last_response: None,
        }
    }

    pub fn observe(&mut self, now: Instant, rtt: Duration) {
        let sample = rtt.as_secs_f64() * 1_000.0;
        match self.srtt_ms {
            Some(previous) => {
                self.rtt_variation_ms =
                    0.75 * self.rtt_variation_ms + 0.25 * (previous - sample).abs();
                self.srtt_ms = Some(0.875 * previous + 0.125 * sample);
            }
            None => {
                self.srtt_ms = Some(sample);
                self.rtt_variation_ms = sample / 2.0;
            }
        }
        self.minimum_rtt_ms = Some(
            self.minimum_rtt_ms
                .map_or(sample, |value| value.min(sample)),
        );
        self.samples += 1;
        self.last_response = Some(now);
    }

    pub fn failure_timeout(&self) -> Duration {
        let estimate = self.srtt_ms.unwrap_or(30.0) + 4.0 * self.rtt_variation_ms;
        Duration::from_secs_f64((estimate / 1_000.0).clamp(0.035, 0.070))
    }

    pub fn healthy(&self, now: Instant) -> bool {
        self.last_response.is_some_and(|last| {
            now.checked_duration_since(last)
                .is_some_and(|age| age <= self.failure_timeout())
        })
    }

    pub fn risk_score(&self) -> f64 {
        self.srtt_ms.unwrap_or(f64::MAX) + 2.0 * self.rtt_variation_ms
    }
}

#[derive(Clone, Debug, Serialize)]
pub struct RecoveryDecision {
    pub primary_path: u8,
    pub alternate_path: Option<u8>,
    pub protect_in_advance: bool,
    pub estimated_recovery_ms: Option<f64>,
    pub state: &'static str,
}

pub fn recovery_decision(
    paths: &[PathState],
    now: Instant,
    exposed_bytes: u64,
    alternate_spare_bits_per_second: f64,
) -> Option<RecoveryDecision> {
    let mut healthy: Vec<_> = paths.iter().filter(|path| path.healthy(now)).collect();
    healthy.sort_by(|left, right| left.risk_score().total_cmp(&right.risk_score()));
    let primary = *healthy.first()?;
    let Some(alternate) = healthy.get(1).copied() else {
        return Some(RecoveryDecision {
            primary_path: primary.path,
            alternate_path: None,
            protect_in_advance: false,
            estimated_recovery_ms: None,
            state: "no-alternate",
        });
    };
    if alternate_spare_bits_per_second <= 0.0 {
        return Some(RecoveryDecision {
            primary_path: primary.path,
            alternate_path: Some(alternate.path),
            protect_in_advance: true,
            estimated_recovery_ms: None,
            state: "insufficient-reserve",
        });
    }
    let estimate = primary.failure_timeout().as_secs_f64()
        + alternate.srtt_ms.unwrap_or(100.0) / 1_000.0
        + exposed_bytes as f64 * 8.0 / alternate_spare_bits_per_second
        + 0.005;
    Some(RecoveryDecision {
        primary_path: primary.path,
        alternate_path: Some(alternate.path),
        protect_in_advance: estimate > 0.100,
        estimated_recovery_ms: Some(estimate * 1_000.0),
        state: if estimate > 0.100 {
            "protect-in-advance"
        } else {
            "reactive-repair"
        },
    })
}

pub fn bind_interface_socket(interface: &str, relay: SocketAddr) -> Result<UdpSocket> {
    if !relay.is_ipv4() {
        bail!("the first lab build supports IPv4 relay addresses only");
    }
    let socket = StdUdpSocket::bind("0.0.0.0:0").context("bind UDP socket")?;
    #[cfg(unix)]
    configure_udp_buffers(&socket)?;
    bind_ipv4_interface(&socket, interface)?;
    socket
        .connect(relay)
        .with_context(|| format!("connect {interface} to {relay}"))?;
    socket.set_nonblocking(true)?;
    UdpSocket::from_std(socket).context("register UDP socket with Tokio")
}

/// Size this socket for short packet bursts without changing host-wide sysctls.
/// Linux accounts approximately twice the requested size for socket metadata.
#[cfg(unix)]
pub fn configure_udp_buffers(socket: &impl std::os::fd::AsRawFd) -> Result<()> {
    let fd = socket.as_raw_fd();
    let set = |option: libc::c_int, bytes: libc::c_int| -> std::io::Result<()> {
        // SAFETY: fd is borrowed from a live socket and the pointer/length
        // describe a local integer for the duration of the syscall.
        let result = unsafe {
            libc::setsockopt(
                fd,
                libc::SOL_SOCKET,
                option,
                (&bytes as *const libc::c_int).cast(),
                std::mem::size_of_val(&bytes) as libc::socklen_t,
            )
        };
        if result == 0 {
            Ok(())
        } else {
            Err(std::io::Error::last_os_error())
        }
    };
    for (option, requested) in [
        (libc::SO_RCVBUF, 4 * 1024 * 1024),
        (libc::SO_SNDBUF, 1024 * 1024),
    ] {
        // macOS can reject requests above its socket allocation ceiling.
        set(option, requested)
            .or_else(|_| set(option, 1024 * 1024))
            .or_else(|_| set(option, 256 * 1024))?;
        #[cfg(target_os = "linux")]
        {
            // The privileged TUN runtime can raise its own socket limit while
            // leaving unrelated services and global buffer limits unchanged.
            let force = if option == libc::SO_RCVBUF {
                libc::SO_RCVBUFFORCE
            } else {
                libc::SO_SNDBUFFORCE
            };
            let _ = set(force, requested); // Unprivileged diagnostic clients retain the normal limit.
        }
    }
    Ok(())
}

#[cfg(target_os = "macos")]
fn bind_ipv4_interface(socket: &StdUdpSocket, interface: &str) -> Result<()> {
    use std::os::fd::AsRawFd;

    bind_ipv4_interface_fd(socket.as_raw_fd(), interface)
}

#[cfg(target_os = "macos")]
pub fn bind_ipv4_interface_fd(fd: std::os::fd::RawFd, interface: &str) -> Result<()> {
    use std::ffi::CString;

    let name = CString::new(interface).context("interface name contains a NUL byte")?;
    // SAFETY: name is a valid NUL-terminated C string for this call.
    let index = unsafe { libc::if_nametoindex(name.as_ptr()) };
    if index == 0 {
        bail!("interface {interface} does not exist");
    }
    let index = index as libc::c_uint;
    // SAFETY: the pointer and length describe the local index value for the
    // duration of setsockopt. IP_BOUND_IF is the macOS IPv4 interface option.
    let result = unsafe {
        libc::setsockopt(
            fd,
            libc::IPPROTO_IP,
            libc::IP_BOUND_IF,
            (&index as *const libc::c_uint).cast(),
            std::mem::size_of_val(&index) as libc::socklen_t,
        )
    };
    if result != 0 {
        return Err(std::io::Error::last_os_error())
            .with_context(|| format!("bind socket to {interface}"));
    }
    Ok(())
}

#[cfg(target_os = "linux")]
fn bind_ipv4_interface(socket: &StdUdpSocket, interface: &str) -> Result<()> {
    use std::os::fd::AsRawFd;

    bind_ipv4_interface_fd(socket.as_raw_fd(), interface)
}

#[cfg(target_os = "linux")]
pub fn bind_ipv4_interface_fd(fd: std::os::fd::RawFd, interface: &str) -> Result<()> {
    use std::ffi::CString;

    let name = CString::new(interface).context("interface name contains a NUL byte")?;
    // SAFETY: the pointer and byte count cover the NUL-terminated interface name.
    let result = unsafe {
        libc::setsockopt(
            fd,
            libc::SOL_SOCKET,
            libc::SO_BINDTODEVICE,
            name.as_ptr().cast(),
            name.as_bytes_with_nul().len() as libc::socklen_t,
        )
    };
    if result != 0 {
        return Err(std::io::Error::last_os_error())
            .with_context(|| format!("bind socket to {interface}"));
    }
    Ok(())
}

#[cfg(not(any(target_os = "macos", target_os = "linux")))]
fn bind_ipv4_interface(_socket: &StdUdpSocket, interface: &str) -> Result<()> {
    bail!("interface binding is not implemented for this OS: {interface}")
}

#[cfg(not(any(target_os = "macos", target_os = "linux")))]
pub fn bind_ipv4_interface_fd(_fd: std::os::fd::RawFd, interface: &str) -> Result<()> {
    bail!("interface binding is not implemented for this OS: {interface}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[cfg(unix)]
    #[test]
    fn udp_burst_buffers_are_configured_on_the_socket() {
        use std::os::fd::AsRawFd;
        let socket = StdUdpSocket::bind("127.0.0.1:0").unwrap();
        configure_udp_buffers(&socket).unwrap();
        for option in [libc::SO_RCVBUF, libc::SO_SNDBUF] {
            let mut bytes: libc::c_int = 0;
            let mut length = std::mem::size_of_val(&bytes) as libc::socklen_t;
            // SAFETY: live socket with correctly sized writable output values.
            let result = unsafe {
                libc::getsockopt(
                    socket.as_raw_fd(),
                    libc::SOL_SOCKET,
                    option,
                    (&mut bytes as *mut libc::c_int).cast(),
                    &mut length,
                )
            };
            assert_eq!(result, 0);
            assert!(bytes >= 256 * 1024, "buffer is only {bytes} bytes");
        }
    }

    #[test]
    fn encrypted_packet_round_trip_and_tamper_rejection() {
        let secret = [7_u8; 32];
        let session = SessionId([9_u8; 16]);
        let mut client = Channel::new(&secret, session, 0, Role::Client).unwrap();
        let mut relay = Channel::new(&secret, session, 0, Role::Relay).unwrap();
        let payload = synthetic_payload(42, 900);
        let packet = client.seal(Kind::Data, 0, 42, 123, &payload).unwrap();
        let opened = relay.open(&packet).unwrap();
        assert_eq!(opened.sequence, 42);
        assert_eq!(opened.payload, payload);

        let mut tampered = client
            .seal(Kind::Data, 0, 43, 124, &synthetic_payload(43, 900))
            .unwrap();
        *tampered.last_mut().unwrap() ^= 1;
        assert!(relay.open(&tampered).is_err());
    }

    #[test]
    fn replay_window_accepts_reordering_once() {
        let mut window = ReplayWindow::new(8);
        assert!(window.mark(10));
        assert!(window.mark(8));
        assert!(!window.mark(8));
        assert!(window.mark(20));
        assert!(!window.mark(10));
    }

    #[test]
    fn replay_ring_matches_reference_for_gaps_duplicates_and_reordering() {
        use std::collections::BTreeSet;
        for width in [1, 3, 8, 65, 8192] {
            let mut window = ReplayWindow::new(width);
            let mut seen = BTreeSet::new();
            let mut high = 0_u64;
            let mut random = 7_u64;
            for _ in 0..30_000 {
                random = random.wrapping_mul(6364136223846793005).wrapping_add(1);
                let counter = match random % 4 {
                    0 => high.saturating_add(random % (width * 2 + 1)),
                    1 => high.saturating_sub(random % (width * 2 + 1)),
                    2 => high.saturating_add(1),
                    _ => high,
                };
                let replay =
                    (counter <= high && high - counter >= width) || seen.contains(&counter);
                assert_eq!(window.contains(counter), replay);
                assert_eq!(window.mark(counter), !replay);
                if !replay {
                    high = high.max(counter);
                    seen.insert(counter);
                    while seen.first().is_some_and(|value| high - value >= width) {
                        seen.pop_first();
                    }
                }
            }
        }
    }

    #[test]
    fn replay_ring_handles_counter_limit_without_saturating_false_positives() {
        let mut window = ReplayWindow::new(8);
        assert!(window.mark(u64::MAX));
        assert!(window.mark(u64::MAX - 7));
        assert!(!window.mark(u64::MAX - 8));
        assert!(window.mark(u64::MAX - 1));
        assert!(!window.mark(u64::MAX));
        assert!(!window.mark(u64::MAX - 1));
        assert!(!window.mark(0));
    }

    #[test]
    fn recovery_budget_reacts_when_the_alternate_loses_capacity() {
        let now = Instant::now();
        let mut fast = PathState::new(0, "fast".into(), "127.0.0.1:1".parse().unwrap());
        let mut steady = PathState::new(1, "steady".into(), "127.0.0.1:2".parse().unwrap());
        fast.observe(now, Duration::from_millis(10));
        steady.observe(now, Duration::from_millis(20));

        let safe =
            recovery_decision(&[fast.clone(), steady.clone()], now, 4_000, 5_000_000.0).unwrap();
        assert!(!safe.protect_in_advance);
        let unsafe_decision = recovery_decision(&[fast, steady], now, 40_000, 1_000_000.0).unwrap();
        assert!(unsafe_decision.protect_in_advance);
    }
}
